// Code generated by "stringer -type=LayerType,BlendMode,ColorDepth,LoopDirection,CelType,FlipBitMask -output=type_string.go"; DO NOT EDIT.

package aseprite

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Image-0]
	_ = x[Group-1]
	_ = x[Tilemap-2]
}

const _LayerType_name = "ImageGroupTilemap"

var _LayerType_index = [...]uint8{0, 5, 10, 17}

func (i LayerType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LayerType_index)-1 {
		return "LayerType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LayerType_name[_LayerType_index[idx]:_LayerType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Normal-0]
	_ = x[Multiply-1]
	_ = x[Screen-2]
	_ = x[Overlay-3]
	_ = x[Darken-4]
	_ = x[Lighten-5]
	_ = x[ColorDodge-6]
	_ = x[ColorBurn-7]
	_ = x[HardLight-8]
	_ = x[SoftLight-9]
	_ = x[Difference-10]
	_ = x[Exclusion-11]
	_ = x[Hue-12]
	_ = x[Saturation-13]
	_ = x[Color-14]
	_ = x[Luminosity-15]
	_ = x[Addition-16]
	_ = x[Subtract-17]
	_ = x[Divide-18]
}

const _BlendMode_name = "NormalMultiplyScreenOverlayDarkenLightenColorDodgeColorBurnHardLightSoftLightDifferenceExclusionHueSaturationColorLuminosityAdditionSubtractDivide"

var _BlendMode_index = [...]uint8{0, 6, 14, 20, 27, 33, 40, 50, 59, 68, 77, 87, 96, 99, 109, 114, 124, 132, 140, 146}

func (i BlendMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_BlendMode_index)-1 {
		return "BlendMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BlendMode_name[_BlendMode_index[idx]:_BlendMode_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NRGBA-32]
	_ = x[Grayscale-16]
	_ = x[Indexed-8]
}

const (
	_ColorDepth_name_0 = "Indexed"
	_ColorDepth_name_1 = "Grayscale"
	_ColorDepth_name_2 = "NRGBA"
)

func (i ColorDepth) String() string {
	switch {
	case i == 8:
		return _ColorDepth_name_0
	case i == 16:
		return _ColorDepth_name_1
	case i == 32:
		return _ColorDepth_name_2
	default:
		return "ColorDepth(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Forward-0]
	_ = x[Reverse-1]
	_ = x[PingPong-2]
	_ = x[PingPongReverse-3]
}

const _LoopDirection_name = "ForwardReversePingPongPingPongReverse"

var _LoopDirection_index = [...]uint8{0, 7, 14, 22, 37}

func (i LoopDirection) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LoopDirection_index)-1 {
		return "LoopDirection(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LoopDirection_name[_LoopDirection_index[idx]:_LoopDirection_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RawUncompressed-0]
	_ = x[LinkedCel-1]
	_ = x[CompressedImage-2]
	_ = x[CompressedTilemap-3]
}

const _CelType_name = "RawUncompressedLinkedCelCompressedImageCompressedTilemap"

var _CelType_index = [...]uint8{0, 15, 24, 39, 56}

func (i CelType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_CelType_index)-1 {
		return "CelType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CelType_name[_CelType_index[idx]:_CelType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FlipX-1]
	_ = x[FlipY-2]
	_ = x[FlipD-4]
}

const (
	_FlipBitMask_name_0 = "FlipXFlipY"
	_FlipBitMask_name_1 = "FlipD"
)

var (
	_FlipBitMask_index_0 = [...]uint8{0, 5, 10}
)

func (i FlipBitMask) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _FlipBitMask_name_0[_FlipBitMask_index_0[i]:_FlipBitMask_index_0[i+1]]
	case i == 4:
		return _FlipBitMask_name_1
	default:
		return "FlipBitMask(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
